name: Tijaraa
description: A classified app
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & icons
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  lottie: ^3.3.1
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  dotted_border: ^2.1.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  firebase_messaging: ^15.1.3
  cloud_firestore: ^5.6.12
  firebase_app_check: ^0.3.2+10

  # Networking & Data
  dio: ^5.8.0+1
  http: ^1.2.2
  collection: ^1.19.1

  # Local storage
  shared_preferences: ^2.0.18
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  path: ^1.9.1

  # State management
  flutter_bloc: ^9.1.1
  provider: ^6.1.2

  # Media & Files
  flick_video_player: ^0.9.0
  video_player: ^2.9.5
  youtube_player_flutter: ^9.1.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  file_picker: ^10.1.2
  open_filex: ^4.7.0
  pdfx: ^2.9.2
  flutter_pdfview: ^1.4.0+1
  syncfusion_flutter_pdf: ^25.2.3

  # Location & Maps
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  google_maps_flutter: ^2.12.1
  device_region: ^1.4.0
  device_info_plus: ^11.4.0

  # Auth & Sign-in
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  sms_autofill: ^2.4.1

  # Notifications
  awesome_notifications: ^0.10.1

  # Web / Preview / Others
  any_link_preview: ^3.0.3
  webview_flutter: ^4.11.0
  flutter_widget_from_html: ^0.16.0
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  in_app_review: ^2.0.10
  android_intent_plus: ^5.3.0
  google_cloud_translation: ^0.0.4

  # Audio / Vibration / Recording
  record: ^6.0.0
  audioplayers: ^6.4.0
  vibration: ^3.1.3

  # Ads
  google_mobile_ads: ^6.0.0

  # Payment Gateways
  flutter_stripe: ^11.5.0
  in_app_purchase: ^3.2.1
  razorpay_flutter: ^1.4.0
  phonepe_payment_sdk: ^3.0.0

  # Utilities
  country_picker: ^2.0.26
  mime_type: ^1.0.1
  permission_handler: ^12.0.0+1
  package_info_plus: ^8.3.0
  uuid: ^4.0.0
  change_app_package_name: ^1.5.0
  flutter_webrtc: ^1.2.0
  connectivity_plus: ^6.0.5

  # Debug tools

dependency_overrides:
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename: ^3.0.0
  curl_logger_dio_interceptor: ^1.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/svg/Logo/splashlogo.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/bottomnav/
    - assets/svg/Logo/
    - assets/svg/Illustrators/
    - assets/svg/payment/
    - assets/fonts/
    - assets/lottie/
    - assets/chat_background/
    - assets/languages/language.json
    - assets/map.png
    - assets/svg/Logo/logo.png
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
